. tab infant_mortality
. summarize infant_mortality
. summarize infant_mortality, detail
. generate inf_mort_mean = infant_mortality
. replace inf_mort_mean = . if inf_mort_mean<24.14
. replace inf_mort_mean = . if inf_mort_mean>26.68
. generate inf_mort_med = infant_mortality
. replace inf_mort_med = . if inf_mort_med<16.58
. replace inf_mort_med = . if inf_mort_med>18.32
. histogram infant_mortality
. generate inf_mort_outliers = infant_mortality
. replace inf_mort_outliers = . if inf_mort_outliers<-44.93
. replace inf_mort_outliers = . if inf_mort_outliers>92.28
. sort infant_mortality 
. generate continent = 0
. replace continent = 1 if iso2c == "AL"
. replace continent = 2 if iso2c=="AF"
. replace continent = 3 if iso2c=="AR"
. replace continent = 2 if iso2c=="AM"
. replace continent = 4 if iso2c=="AU"
. replace continent = 1 if iso2c=="AT"
. replace continent = 2 if iso2c=="AZ"
. replace continent = 2 if iso2c=="BH"
. replace continent = 2 if iso2c=="BD"
. replace continent = 1 if iso2c=="BY"
. replace continent = 1 if iso2c=="BE"
. replace continent = 2 if iso2c=="BT"
. replace continent = 3 if iso2c=="BO"
. replace continent = 1 if iso2c=="BA"
. replace continent = 3 if iso2c=="BR"
. replace continent = 1 if iso2c=="BG"
. replace continent = 3 if iso2c=="KH"
. replace continent = 5 if iso2c=="CA"
. replace continent = 3 if iso2c=="CN"
. replace continent = 2 if iso2c=="CN"
. replace continent = 3 if iso2c=="CO"
. replace continent = 3 if iso2c=="CR"
. replace continent = 1 if iso2c=="HR"
. replace continent = 5 if iso2c=="CU"
. replace continent = 1 if iso2c=="CY"
. replace continent = 1 if iso2c=="CZ"
. replace continent = 1 if iso2c=="DK"
. replace continent = 3 if iso2c=="EC"
. replace continent = 1 if iso2c=="FI"
. replace continent = 4 if iso2c=="FJ"
. replace continent = 1 if iso2c=="FR"
. replace continent = 1 if iso2c=="GE"
. replace continent = 1 if iso2c=="EE"
. replace continent = 1 if iso2c=="DE"
. replace continent = 1 if iso2c=="GR"
. replace continent = 3 if iso2c=="GT"
. replace continent = 3 if iso2c=="GY"
. replace continent = 5 if iso2c=="HT"
. replace continent = 3 if iso2c=="HN"
. replace continent = 2 if iso2c=="HK"
. replace continent = 1 if iso2c=="HU"
. replace continent = 2 if iso2c=="ID"
. replace continent = 2 if iso2c=="IN"
. replace continent = 2 if iso2c=="IR"
. replace continent = 2 if iso2c=="IQ"
. replace continent = 2 if iso2c=="IL"
. replace continent = 1 if iso2c=="IE"
. replace continent = 1 if iso2c=="IT"
. replace continent = 5 if iso2c=="JM"
. replace continent = 1 if iso2c=="JP"
. replace continent = 1 if iso2c=="JO"
. replace continent = 1 if iso2c=="KZ"
. replace continent = 1 if iso2c=="KP"
. replace continent = 2 if iso2c=="JP"
. replace continent = 2 if iso2c=="JO"
. replace continent = 2 if iso2c=="KZ"
. replace continent = 2 if iso2c=="KP"
. replace continent = 2 if iso2c=="KR"
. replace continent = 1 if iso2c=="XK"
. replace continent = 2 if iso2c=="KW"
. replace continent = 2 if iso2c=="KG"
. replace continent = 2 if iso2c=="LA"
. replace continent = 1 if iso2c=="LV"
. replace continent = 2 if iso2c=="LB"
. replace continent = 1 if iso2c=="LT"
. replace continent = 1 if iso2c=="LU"
. replace continent = 2 if iso2c=="MO"
. replace continent = 2 if iso2c=="MY"
. replace continent = 5 if iso2c=="MX"
. replace continent = 1 if iso2c=="ME"
. replace continent = 1 if iso2c=="MD"
. replace continent = 2 if iso2c=="MN"
. replace continent = 2 if iso2c=="MM"
. replace continent = 2 if iso2c=="NP"
. replace continent = 1 if iso2c=="NL"
. replace continent = 4 if iso2c=="NZ"
. replace continent = 3 if iso2c=="NI"
. replace continent = 1 if iso2c=="NO"
. replace continent = 2 if iso2c=="OM"
. replace continent = 2 if iso2c=="PK"
. replace continent = 5 if iso2c=="PA"
. replace continent = 4 if iso2c=="PG"
. replace continent = 3 if iso2c=="PY"
. replace continent = 3 if iso2c=="PE"
. replace continent = 2 if iso2c=="PH"
. replace continent = 1 if iso2c=="PO"
. replace continent = 1 if iso2c=="PL"
. replace continent = 1 if iso2c=="PT"
. replace continent = 5 if iso2c=="PR"
. replace continent = 2 if iso2c=="QA"
. replace continent = 1 if iso2c=="RO"
. replace continent = 1 if iso2c=="RU"
. replace continent = 2 if iso2c=="SA"
. replace continent = 1 if iso2c=="RS"
. replace continent = 2 if iso2c=="SG"
. replace continent = 1 if iso2c=="SK"
. replace continent = 1 if iso2c=="SI"
. replace continent = 1 if iso2c=="ES"
. replace continent = 2 if iso2c=="LK"
. replace continent = 1 if iso2c=="SE"
. replace continent = 1 if iso2c=="CH"
. replace continent = 2 if iso2c=="SY"
. replace continent = 2 if iso2c=="TJ"
. replace continent = 2 if iso2c=="TH"
. replace continent = 2 if iso2c=="TL"
. replace continent = 1 if iso2c=="TR"
. replace continent = 1 if iso2c=="UA"
. replace continent = 2 if iso2c=="AE"
. replace continent = 1 if iso2c=="GB"
. replace continent = 3 if iso2c=="UY"
. replace continent = 2 if iso2c=="UZ"
. replace continent = 3 if iso2c=="VE"
. replace continent = 2 if iso2c=="VN"
. replace continent = 2 if iso2c=="PS"
. replace continent = 2 if iso2c=="YE"
. order iso2c country continent 
. replace continent = 2 if iso2c=="KH"
. replace continent = 3 if iso2c=="CI"
. replace continent = 3 if iso2c=="CL"
. replace continent = 0 if iso2c=="CI"
. replace continent = 5 if iso2c=="DO"
. replace continent = 3 if iso2c=="SV"
. replace continent = 1 if iso2c=="MK"
. replace continent = 3 if iso2c=="TT"
. replace continent = 2 if iso2c=="TM"
. by continent, sort : summarize infant_mortality
. by continent, sort : summarize infant_mortality, detail
. regress infant_mortality pct_women_in_parliament
. regress infant_mortality pct_women_in_parliament political_stability i.continent


